### PR TITLE
[MOD-2328] Support upload-tasks, move session and configuration to own proxy, major refactoring

### PR DESCRIPTION
**Pull request by hansemannn**
Changes in this PR:
- [x] Add new method `upload` to support background-uploads
- [x] Add new methods `flush` and `reset` for an improved resources handling
- [x] Deprecate `backgroundDownloadTaskWithURL` in favor of `addBackgroundDownloadTask`
- [x] Move `URLSession.Session` and `URLSession.SessionConfiguration` to own namespaces
- [x] Deprecate old single-argument constructor for sessions and session-configurations
- [x] Introduce object-based constructors to incorporate the new namespaces properly

The example file has already been updated, check it out [here](https://github.com/hansemannn/ti.urlsession/blob/a9c5e8160986b28e2e9a14244b555f18d73c23ab/ios/example/app.js).

### CODE REVIEW

**Comment by hansemannn** [comment]
@rlustemberg Can you confirm the API's work for you (excluding the event in the SDK)? We also need to ensure all old methods still work, but only show the deprecated logs.

**Comment by rlustemberg** [comment]
Yes, it all works perfectly.

**Comment by rlustemberg** [comment]
I might still need to the session configuration one using arguments instead of the dictionary. I'll confirm in a few minutes

**Comment by rlustemberg** [comment]
Deprecated and new methods both work!

**Comment by hansemannn** [comment]
Good catch! Updated.

**Comment by hansemannn** [comment]
1. We only support iOS 8+ since SDK 6.0.0+, so that should be fine.
2. I don't understand the sentence, sorry.

**Comment by vijaysingh-axway** [comment]
As we can use ti.urlsession version 2.1.0 with Titanium SDK 6.0.x and lower version as well. 
So in point 2 I just want to say rather "since: 6.1.0" it should be "since: 2.1.0" as the deprecated method is part of ti.urlsession module .

**Comment by hansemannn** [comment]
Oh, yeah that should be new for you, sorry! So we usually use the version of the SDK where the new module version is bundled with (same for Ti.Facebook and Ti.Map for example). But I prefer to write the module as well tbh, we could improve that over this year. But for now, we'd just use the SDK that has the prepackaged module, which would be 6.1.0. Thanks!

**Comment by hansemannn** [comment]
Done!

**Comment by vijaysingh-axway** [comment]
@hansemannn  I don't have permission to add label and reviewer in this . Can you please provide the same.

**Comment by hansemannn** [comment]
You have, but the repo didn't have that label created so far.

**Pull request merged**
